// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"CustomLogo","status":true,"description":"Shows RPG Maker and user logos at the start of the game.","parameters":{"logo1":"","logo1ImageName":"MadeWithMv","logo1Skippable":"true","logo1Coordinate":"","logo1X":"408","logo1Y":"312","logo1Origin":"0.5","logo1Time":"","logo1FadeinFrames":"12","logo1FadeoutFrames":"12","logo1DurationFrames":"120","logo2":"","logo2ImageName":"","logo2Skippable":"true","logo2Coordinate":"","logo2X":"408","logo2Y":"312","logo2Origin":"0.5","logo2Time":"","logo2FadeinFrames":"12","logo2FadeoutFrames":"12","logo2DurationFrames":"120","logo3":"","logo3ImageName":"","logo3Skippable":"true","logo3Coordinate":"","logo3X":"408","logo3Y":"312","logo3Origin":"0.5","logo3Time":"","logo3FadeinFrames":"12","logo3FadeoutFrames":"12","logo3DurationFrames":"120","allowTotalSkip":"true"}},
{"name":"BlueGrail_UI","status":true,"description":"Game font, item-only item scene, and hidden menu gold.","parameters":{}},
{"name":"BlueGrail_MessageBust","status":true,"description":"Adds message bust images and centered message lines.","parameters":{}},
{"name":"BlueGrail_EventFloat","status":true,"description":"Adds visual-only floating offsets to map events.","parameters":{}},
{"name":"BlueGrail_MapLineTriggers","status":true,"description":"Handles Map002 x-line triggers, path movement, and camera focus helpers.","parameters":{}},
{"name":"BlueGrail_SnowballPuzzle","status":true,"description":"Handles rolling snowballs for the Act 2 avalanche escape puzzle.","parameters":{}}
];
